image:
- Visual Studio 2019
- macOS
- Ubuntu

skip_branch_with_pr: true
stack: python 3.10

environment:
  GITHUB_TOKEN:
    secure: c2JkUCkIoFmqWgf+a9ZZChx9WZXo9rI5xo7cG2xW7St8ybkKMs+FqCm6QemENaAU

install:
- pip install -r requirements.txt

build_script:
- flet pack main.py --name PropScoreEditor --product-name PropScoreEditor

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a PropScoreEditor-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: PropScoreEditor-windows.zip

#
#   macOS package
# 
-
  matrix:
    only:
    - image: macOS

  after_build:
  - tar -czvf PropScoreEditor-macos.tar.gz -C dist PropScoreEditor.app

  artifacts:
  - path: PropScoreEditor-macos.tar.gz

#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  - tar -czvf PropScoreEditor-linux.tar.gz -C dist PropScoreEditor

  artifacts:
  - path: PropScoreEditor-linux.tar.gz
