name: python build

on:
  push:
    branches:
      - 'main'
  workflow_dispatch: ~

jobs:
  Python-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install -r gcsim/requirements.txt

      - name: Check GCSIM scripts
        run: |
          python gcsim/main.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          push: 'origin remote --force'
          new_branch: 'remote'
          message: ':sparkles: Update resources'
          fetch: false
